repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format 
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy
        additional_dependencies: [
            types-requests>=2.31.0,
            types-pillow>=10.2.0,
            types-pyyaml>=6.0.12.12,
            types-setuptools>=69.1.0,
            spacy>=3.0.0
        ] 