anki:
  deck:
    filename: "spanish_vocabulary.apkg"
    name: "Spanish Vocabulary"
    id: 7262245122
  model_id: 2600788583

paths:
  data:
    dir: data
    raw_vocab: raw_vocab.txt
    sanitized_vocab: sanitized_vocab.txt
    curator_history: curator_history.json
  output:
    dir: output
    terms:
      dir: terms
    deck: "spanish_vocabulary.apkg"

images:
  max_dimension: 1024  # Maximum size for Anki card images

openai:
  model: "gpt-4o"
  temperature: 0.7

spacy:
  model_name: "es_core_news_md"