anki_deck:
  name: "Spanish Vocabulary"
  id: 7262245122

paths:
  data:
    dir: data
    raw_vocab: raw_vocab.txt
    cleaned_vocab: cleaned_vocab.txt
    selector_history: vocab_selector_history.json
  output:
    dir: output
    terms:
      dir: terms
      components:
        dictionary_entry: merriam_webster_entry.json
        augmented_term: llm_augmented_term.json
        pronunciation: pronunciation.mp3
        image: image.png
    deck: "spanish_vocabulary.apkg"

openai:
  model: "gpt-4o"
  temperature: 0.7

spacy:
  model_name: "es_core_news_md"